Repository GSG-CF04/ToDoList_team7, pull requests merged in 2021-11, with the labels that each got.

#3 structuring files
  css/style.css
  index.html
  js/script.js
Labels: awaiting review

#4 add readme file
  README.md
Labels: Done

#7 adding css and html files
  css/style.css
  img/Vector.png
  img/clarity_list-outline-badged.png
  index.html
Labels: awaiting review

#8 javascript adding
  img/check.png
  img/delete.png
  img/ic_baseline-light-mode.png
  index.html
  js/dark.js
  js/script.js
Labels: awaiting review

#14 adding functions to js code
  js/script.js
Labels: approved

#12 adding responsive
  css/style.css
  index.html
Labels: approved

#17 editing-add-and-delete-function
  js/script.js
Labels: awaiting review

#19 edit-delete-function
  js/script.js
Labels: approved

#20 Create-the-check-btn
  css/style.css
  js/script.js
Labels: awaiting review

#23 Function edit and reset
  index.html
  js/script.js
Labels: awaiting review
